export const CATEGORIES_REQUESTED = "CATEGORIES_REQUESTED";
export const CATEGORIES_RECEIVED = "CATEGORIES_RECEIVED";
export const CATEGORIES_FAILED = "CATEGORIES_FAILED";
export const CATEGORIES_CREATED_REQUESTED = "CATEGORIES_CREATED_REQUESTED";
export const CATEGORIES_CREATED = "CATEGORIES_CREATED";
export const CATEGORIES_CREATED_FAILED = "CATEGORIES_CREATED_FAILED";
export const CATEGORIES_PATCH_REQUESTED = "CATEGORIES_PATCH_REQUESTED";
export const CATEGORIES_PATCH = "CATEGORIES_PATCH";
export const CATEGORIES_PATCH_FAILED = "CATEGORIES_PATCH";
export const CATEGORIES_DELETE_REQUESTED = "CATEGORIES_DELETE_REQUESTED";
export const CATEGORIES_DELETE = "CATEGORIES_DELETE";
export const CATEGORIES_DELETE_FAILED = "CATEGORIES_DELETE_FAILED";

export const PROPERTIES_REQUESTED = "PROPERTIES_REQUESTED";
export const PROPERTIES_RECEIVED = "PROPERTIES_RECEIVED";
export const PROPERTIES_FAILED = "PROPERTIES_FAILED";
export const PROPERTIES_CREATED_REQUESTED = "PROPERTIES_CREATED_REQUESTED";
export const PROPERTIES_CREATED = "PROPERTIES_CREATED";
export const PROPERTIES_CREATED_FAILED = "PROPERTIES_CREATED_FAILED";
export const PROPERTIES_PATCH_REQUESTED = "PROPERTIES_PATCH_REQUESTED";
export const PROPERTIES_PATCH = "PROPERTIES_PATCH";
export const PROPERTIES_PATCH_FAILED = "PROPERTIES_PATCH";
export const PROPERTIES_DELETE_REQUESTED = "PROPERTIES_DELETE_REQUESTED";
export const PROPERTIES_DELETE = "PROPERTIES_DELETE";
export const PROPERTIES_DELETE_FAILED = "PROPERTIES_DELETE_FAILED";


