export const ROOT_BUCKETS_REQUESTED = "ROOT_BUCKETS_REQUESTED";
export const ROOT_BUCKETS_RECIEVED = "ROOT_BUCKETS_RECIEVED";
export const ROOT_BUCKETS_FAILED = "ROOT_BUCKETS_FAILED";
export const ROOT_BUCKETS_TOOGLE_MENU = "ROOT_BUCKETS_TOOGLE_MENU";

export const CONTENT_REQUESTED = "CONTENT_REQUESTED";
export const CONTENT_RECIEVED = "CONTENT_RECIEVED";
export const CONTENT_FAILED = "CONTENT_FAILED";

export const QUERY_ACCEPTED = "QUERY_ACCEPTED";
export const QUERY_ADD_TERM = "QUERY_ADD_TERM";
export const QUERY_ADD_ATTRIBUTE = "QUERY_ADD_ATTRIBUTE";
export const QUERY_REMOVE_ATTRIBUTE = "QUERY_REMOVE_ATTRIBUTE";
export const QUERY_ADD_CAT = "QUERY_ADD_CAT";
export const QUERY_REMOVE_CAT = "QUERY_REMOVE_CAT";

export const WIZARD_SET_CATEGORY = "WIZARD_SET_CATEGORY";
export const WIZARD_PROPERTY_RESET = "WIZARD_PROPERTY_RESET";
export const WIZARD_PROPERTY_REQUSTED = "WIZARD_PROPERTY_REQUSTED";
export const WIZARD_PROPERTY_RECEIVED = "WIZARD_PROPERTY_RECEIVED";
export const WIZARD_PROPERTY_FAILED = "WIZARD_PROPERTY_FAILED";

export const WIZARD_SET_PROPERTY = "WIZARD_SET_PROPERTY";
export const WIZARD_DELETE_PROPERTY = "WIZARD_DELETE_PROPERTY";
export const WIZARD_SET_NAME = "WIZARD_SET_NAME";
export const WIZARD_SET_DESCRIPTION = "WIZARD_SET_DESCRIPTION";

export const WIZARD_CREATE_MODULE_STARTED = "WIZARD_CREATE_MODULE_STARTED";
export const WIZARD_CREATE_MODULE_COMPLETED = "WIZARD_CREATE_MODULE_COMPLETED";
export const WIZARD_CREATE_MODULE_FAILED = "WIZARD_CREATE_MODULE_FAILED";
export const WIZARD_RESET = "WIZARD_RESET";

export const WIZARD_CATEGORY_STEP = "WIZARD_CATEGORY_STEP";
export const WIZARD_OPTION_STEP = "WIZARD_OPTION_STEP";
export const WIZARD_PHOTO_STEP = "WIZARD_PHOTO_STEP";

export const WIZARD_PHOTO_UPLOAD_STARTED = "WIZARD_PHOTO_UPLOAD_STARTED";
export const WIZARD_PHOTO_UPLOAD_COMPLETED = "WIZARD_PHOTO_UPLOAD_COMPLETED";
export const WIZARD_PHOTO_UPLOAD_FAILED = "WIZARD_PHOTO_UPLOAD_FAILED";

export const WIZARD_ARTIFACT_PENDING = "WIZARD_ARTIFACT_PENDING";
export const WIZARD_ARTIFACT_ERROR = "WIZARD_ARTIFACT_ERROR";
export const WIZARD_ARTIFACT_COMPLETED = "WIZARD_ARTIFACT_COMPLETED";

export const WIZARD_ARTIFACT_MODULE_SET = "WIZARD_ARTIFACT_MODULE_SET";